# Generated by Django 3.2.25 on 2025-02-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
